### ISSUE TITLE
Design aspects of the EKF for BLMC robots

### ISSUE THREAD

**Issue by ahmadgazar** [machines-in-motion/mim_estimation#5]
## Goal:
The aim of this epic is to discuss the design aspects of implementing a generic KF for BLMC robots (e.g. solo, bolt). 

## issues breakdown:
- [x] [Decide for the quaternion convention](https://github.com/machines-in-motion/robot_estimation/issues/4)
- [x] [Decide for simulating IMU using pybullet](https://github.com/machines-in-motion/robot_estimation/issues/3)
- [x] [Decide which Kalman filter approach to use for BLMC robots](https://github.com/machines-in-motion/robot_estimation/issues/6)
- [x] [Decide for the mathematical notation and add the technical report of the Kalman Filter](https://github.com/machines-in-motion/robot_estimation/issues/7)

**Comment by nrotella** [comment]
I feel there is one more thing we should discuss: which actual paper to implement. Pasting this from email I wrote to the rest of the Solo team earlier in 2020:

> After thinking a little more, I actually think that for point contacts, the Pronto approach may perform better (especially because quadrupeds typically need to deal with a lot more foot slippage) and be easier to implement. Here is a very basic history of legged odometric estimators and their differences, in order:

>1. In [Bloesch et al 2012](https://infoscience.epfl.ch/record/181040/files/Bloesch-Siegwart_State__IMU_2012.pdf) a point foot filter which integrated IMU and leg odometry was introduced. It explicitly included foot position in the EKF state and add/dropped measurements from the EKF update based on foot contact states.
>2. In [Bloesch et al 2013](https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/75852/eth-7743-01.pdf) the same filter was modified to remove the foot position states from the EKF and instead use the contact constraint over a short dt to compute a base velocity measurement instead. This simplified the filter implementation and allowed adding a validation gate on the velocity measurement to reject measurements from slipping feet.
>3. In [Rotella et al 2014](https://arxiv.org/pdf/1402.5450.pdf) we extended Bloesch et al 2012 to explicitly include foot orientation measurements for the humanoid flat feet. In retrospect we may have wanted to start from Bloesch et al 2013 and eliminate the foot position/orientation states from the filter entirely but this wasn't published when we started, and it seemed less relevant for a humanoid which makes pretty stable contacts.
>4. In [Fallon et al 2014](https://www.research.ed.ac.uk/portal/files/18903340/14_fallon_humanoids.pdf) essentially the same filter from Bloesch et al 2013 was extended to include LIDAR corrections for absolute base pose drift. Since Atlas has a really high precision gyroscope, they didn't care about including foot orientation measurements for base orientation corrections, so it's the same as a point foot filter.
>5. Skipping ahead some years, [Pronto](https://www.robots.ox.ac.uk/~mobile/drs/Papers/2020FRONTIERS_camurri.pdf) derives from Fallon et al 2014 but includes visual odometry as well, however the kinematic filter at the core is basically the same. They include another previous work from Camurri et al 2017 which adds contact estimation too which is nice. But fundamentally, the quadruped kinematic filter is the same as Bloesch et al 2013.

>I believe I now have access to your repos (thank you!) and can take a look at what's in there. For Solo, maybe it makes more sense to try using one of the filters shown to work well on quadrupeds, all derived from Bloesch et al 2013. It's not that much different than what I did, but quite a bit simpler to implement because it doesn't include foot states directly in the filter. For humanoids (is Hermes still in action?) it may help to have foot orientation measurements, especially with a cheaper IMU than what's on Atlas, but then you have a different filter for quadruped vs humanoid. Even with Pronto the filters are different between the two robot types but only in how the measurements are performed.

Overall I think for a quadruped like Solo and even a humanoid like Bolt, both of which are very dynamic and make lots of frequent, unstable contacts, it makes more sense to go with something based on Bloesch et al 2013. This basically means the foot positions are not included explicitly in the filter, and instead get used to compute a base velocity measurement. For humanoids, as Pronto shows, you can do the same thing and forget including foot orientations or measurements. If we're basically starting from scratch anyway, I think for a robot like Solo it makes more sense to implement this slightly different EKF.

**Comment by ahmadgazar** [comment]
Very nice. I agree, will add this issue to the epic as well. I didn't read Bloesch et al 2013, it's based on a UKF however (which yes way better in my opinion).

**Comment by ahmadgazar** [comment]
I moved the comment of @nrotell , and my reply in this [issue](https://github.com/machines-in-motion/robot_estimation/issues/6).

**Comment by ahmadgazar** [comment]
All the above tasks have been achieved. We can start proceeding testing the implementation in a separate to do.
